baseURL = 'https://kaeru.no'
languageCode = 'en-us'
title = 'Kaeru'
theme = 'rusty-typewriter'

[params.author]
name = 'Nuno Mendes'

[params.rtwt.home]
showBio = true
showAuthorImg = true

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 1
