baseURL = 'https://kaeru.no'
languageCode = 'en-us'
title = 'Kaeru'
theme = 'rusty-typewriter'


[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 1

[[menus.main]]
name = 'About'
pageRef = '/about.md'
weight = 2
